### ISSUE TITLE
Throw exception py4j.Py4JException: Method toPMMLByteArray

### ISSUE THREAD

**Issue by xuande** [jpmml/pyspark2pmml#10]
Python code
```
from pyspark.ml.classification import RandomForestClassifier
rfc = RandomForestClassifier(labelCol=label_col, featuresCol="features", maxDepth=15, maxBins=80)
model = rfc.fit(train_df)

from jpmml_sparkml import toPMMLBytes
pmmlBytes = toPMMLBytes(sc, data_df, model)
print(pmmlBytes.decode("UTF-8"))
```
output
```
An error occurred while calling z:org.jpmml.sparkml.ConverterUtil.toPMMLByteArray. Trace:
py4j.Py4JException: Method toPMMLByteArray([class org.apache.spark.sql.types.StructType, class org.apache.spark.ml.classification.RandomForestClassificationModel]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:339)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)


Traceback (most recent call last):
  File "/data/jpmml-sparkml-package/target/jpmml_sparkml-1.2rc0-py3.5.egg/jpmml_sparkml/__init__.py", line 17, in toPMMLBytes
    return javaConverter.toPMMLByteArray(javaSchema, javaPipelineModel)
  File "/usr/hdp/2.6.1.0-129/spark2/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/hdp/2.6.1.0-129/spark2/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/hdp/2.6.1.0-129/spark2/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 323, in get_return_value
    format(target_id, ".", name, value))
py4j.protocol.Py4JError: An error occurred while calling z:org.jpmml.sparkml.ConverterUtil.toPMMLByteArray. Trace:
py4j.Py4JException: Method toPMMLByteArray([class org.apache.spark.sql.types.StructType, class org.apache.spark.ml.classification.RandomForestClassificationModel]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:339)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by vruusmann** [comment]
The signature of the converter method is `toPMMLByteArray(org.apache.spark.sql.types.StructType, org.apache.spark.ml.PipelineModel)`. You're trying to pass `RandomForestClassificationModel` instead of `PipelineModel`, hence the method resolution fails.

You can make everything work by wrapping Random Forest classifier into a single-step pipeline:
```Python
pipeline = Pipeline(stages = [RandomForestClassifier()])
pipelineModel = pipeline.fit(df)

pmmlBytes = toPMMLBytes(sc, df, pipelineModel)
```

**Comment by vruusmann** [comment]
I'm keeping this issue open, as it points out the needs that perhaps the signature of the converter method should be relaxed to `toPMMLByteArray(StructType, Model)`. Then a single-step PipelineModel would be assumed internally.

Also, the JPMML-SkLearn library accepts "raw" model objects, so why shouldn't the JPMML-SparkML library do the same?

**Comment by vruusmann** [comment]
As of late June 2018, the JPMML-SparkML library only supports PMML generation via the `org.jpmml.sparkml.PMMLBuilder` helper class. See README.md for code example(s).
