### ISSUE TITLE
buildByteArray and XML

### ISSUE THREAD

**Issue by aliware50** [jpmml/pyspark2pmml#28]
my code look like this：
```python
Pmml_builder = PMMLBuilder(sc,train_df,pip_lr_model).putOption(LR, "compact", True)
pmml_bytes = Pmml_builder.buildByteArray()
```
error：
```
Traceback (most recent call last):
  File "LR1.py", line 78, in main
    pmml_bytes = Pmml_builder.buildByteArray()
  File "/worker/fmd_dw_zxx.python-2.7-ucs4.zip/python-2.7-ucs4/lib/python2.7/site-packages/pyspark2pmml/__init__.py", line 23, in buildByteArray
    return self.javaPmmlBuilder.buildByteArray()
  File "/worker/py4j-0.10.6-src.zip/py4j/java_gateway.py", line 1160, in __call__
  File "/worker/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/worker/py4j-0.10.6-src.zip/py4j/protocol.py", line 320, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o397.buildByteArray.
: java.lang.NoSuchMethodError: com.sun.xml.bind.v2.runtime.output.UTF8XmlOutput.<init>(Ljava/io/OutputStream;[Lcom/sun/xml/bind/v2/runtime/output/Encoded;Lcom/sun/xml/bind/marshaller/CharacterEscapeHandler;)V
```
Thanks！

**Comment by vruusmann** [comment]
Looks like some chinese text encoding issue - the second argument to `UTF8XmlOutput` should be a string, but currently appears to be an array of `Encoded` plus `CharacterEscapeHandler` objects.

What is your:

1. PySpark2PMML package version?
2. Apache Spark version?
3. Python version?

**Comment by vruusmann** [comment]
In general, I don't do technical support for non-latin alphabet languages.

If you're not my customer, then you need to do your own troubleshooting in such niche areas.
