### ISSUE TITLE
how can i add a customed transformer in pyspark and export a pipeline which include it as pmml

### ISSUE THREAD

**Issue by Toyben** [jpmml/pyspark2pmml#32]

**Comment by vruusmann** [comment]
This question has been answered many times already (here in GitHub issues and in the JPMML mailing list).

Please use GitHub search and/or Google search (eg. "spark pmml custom transformer").

For example, https://github.com/jpmml/jpmml-sparkml/issues/98

**Comment by Toyben** [comment]
```scala
from pyspark.ml.linalg import SparseVector, DenseVector
from pyspark.ml.classification import GBTClassifier
from pyspark.ml import Pipeline
from pyspark.ml.feature import StandardScaler, Transformer

data1 = spark.createDataFrame([(1, SparseVector(10, (0,1,7),(1.0,1.6,0.3)), DenseVector([1.0,0.1]))
                      ,(0, SparseVector(10, (0,2,9),(0.2,2.1,0.7)), DenseVector([1.0,0.1]))
                      ,(1, SparseVector(10, (1,3,4),(2.0,1.6,-1.1)), DenseVector([1.0,0.1]))
                      ,(0, SparseVector(10, (2,5,7),(-0.2,-1.3,2.0)), DenseVector([1.0,0.1]))
                      ,(0, SparseVector(10, (3,7,8),(-0.4,2.4,-0.2)), DenseVector([1.0,0.1]))
                      ,(1, SparseVector(10, (1,2,3),(1.1,0.6,0.4)), DenseVector([1.0,0.1]))
                      ,(0, SparseVector(10, (0,2,3),(-0.7,0.3,2.2)), DenseVector([1.0,0.1]))
                      ,(1, SparseVector(10, (1,2,4),(-0.2,0.1,1.3)), DenseVector([1.0,0.1]))
                      ,(0, SparseVector(10, (5,7,9),(1.1,-1.1,-0.3)), DenseVector([1.0,0.1]))
                      ,(1, SparseVector(10, (1,3,5),(-0.6,0.7,0.2)), DenseVector([1.0,0.1]))
                      ,(1, SparseVector(10, (1,3,4),(2.0,1.6,-1.1)), DenseVector([1.0,0.1]))
                      ,(0, SparseVector(10, (2,5,7),(-0.2,-1.3,2.0)), DenseVector([1.0,0.1]))
                      ,(0, SparseVector(10, (3,7,8),(-0.4,2.4,-0.2)), DenseVector([1.0,0.1]))
                      ,(1, SparseVector(10, (1,2,3),(1.1,0.6,0.4)), DenseVector([1.0,0.1]))
                      ,(1, SparseVector(10, (1,3,4),(2.0,1.6,-1.1)), DenseVector([1.0,0.1]))
                      ,(0, SparseVector(10, (2,5,7),(-0.2,-1.3,2.0)), DenseVector([1.0,0.1]))
                      ,(0, SparseVector(10, (3,7,8),(-0.4,2.4,-0.2)), DenseVector([1.0,0.1]))
                      ,(1, SparseVector(10, (1,2,3),(1.1,0.6,0.4)), DenseVector([1.0,0.1]))
                      ], ["label", "feat_1", "feat_2"])

class myTransformer(Transformer):
    def __init__(self):
        super().__init__()
    def transform(self, dataset):
        standard = StandardScaler(inputCol= "feat_1", outputCol="feat_1", withStd=True, withMean=False)
        return dataset.withColumn("test", lit(1))

mt = myTransformer()
model_params = {"maxDepth":3
                ,"maxBins":32
                ,"lossType":"logistic"
                ,"maxIter": 10
                ,"stepSize": 0.01
                ,"featuresCol": "feat_1"
                ,"subsamplingRate": 0.5
                }
gbdt = GBTClassifier(**model_params)

pipeline = Pipeline(stage=[mt, gbdt])
model = pipeline.fit(data1)

from pyspark2pmml import PMMLBuilder
pmmlBuilder = PMMLBuilder(sc, data1, model).putOption(gbdt, "compact", True)
```

then i got an Error like this:
```
     Traceback (most recent call last):
          File "<stdin>", line 1, in <module>
          File "C:\Users\mycomputer\${path}\Python36\lib\site-packages\pyspark2pmml\__init__.py", line 11, in __init__
                    javaPipelineModel = pipelineModel._to_java()
          File "C:\spark-3.0.1-bin-hadoop2.7\python\pyspark\ml\pipeline.py", line 365, in _to_java
          java_stages[idx] = stage._to_java()
     AttributeError: 'myTransformer' object has no attribute '_to_java'
```

**Comment by vruusmann** [comment]
> AttributeError: 'myTransformer' object has no attribute '_to_java'

Like the error message says, you need to add the `_to_java` attribute to the PySpark wrapper class of your custom transformer Scala class.
