### ISSUE TITLE
bug found in spark2.4.6 - hadoop2.7.7 - python3.6

### ISSUE THREAD

**Issue by gxlzlihao** [jpmml/pyspark2pmml#35]
After moving jpmml-sparkml-executable-1.5.12.jar to ${SPARK_HOME}/jars folder, I got the following error messages when I started pyspark shell with command "./bin/pyspark"

Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/apache/spark/spark-2.4.6-bin-hadoop2.7/jars/jpmml-sparkml-executable-1.5.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/apache/spark/spark-2.4.6-bin-hadoop2.7/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/apache/hadoop/hadoop-2.7.7/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
Exception in thread "main" java.lang.StackOverflowError
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
        at org.slf4j.impl.JDK14LoggerFactory.getLogger(JDK14LoggerFactory.java:62)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:329)
        at org.slf4j.bridge.SLF4JBridgeHandler.getSLF4JLogger(SLF4JBridgeHandler.java:202)
        at org.slf4j.bridge.SLF4JBridgeHandler.publish(SLF4JBridgeHandler.java:293)
        at java.util.logging.Logger.log(Logger.java:738)
        at org.slf4j.impl.JDK14LoggerAdapter.log(JDK14LoggerAdapter.java:582)
        at org.slf4j.impl.JDK14LoggerAdapter.log(JDK14LoggerAdapter.java:632)
        at org.slf4j.bridge.SLF4JBridgeHandler.callLocationAwareLogger(SLF4JBridgeHandler.java:221)
        at org.slf4j.bridge.SLF4JBridgeHandler.publish(SLF4JBridgeHandler.java:303)
        at java.util.logging.Logger.log(Logger.java:738)
```

**Comment by gxlzlihao** [comment]
I could succeeded running the pyspark code with this command "./bin/pyspark --jars ./jpmml-sparkml-executable-1.5.12.jar"

**Comment by vruusmann** [comment]
Could be related to https://github.com/jpmml/jpmml-sparkml/issues/111

Both issues are about Apache Spark 2.4.X, where there appears to be an intruding SLF4J library.

However, this issue really looks critical, because conflicting SLF4J dependencies appear to be generating an infinite call loop (ie. there is an `StackOverflowError` being thrown).

**Comment by vruusmann** [comment]
> After moving jpmml-sparkml-executable-1.5.12.jar to ${SPARK_HOME}/jars folder

You're not supposed to do that - the `-executable` suffix indicates that this JAR file is supposed to serve as an executable Java application, not as a shareable library.

**Comment by vruusmann** [comment]
Should be fixed in https://github.com/jpmml/jpmml-sparkml/issues/111
