### ISSUE TITLE
py4j.protocol.Py4JError: org.jpmml.sparkml.PMMLBuilder does not exist in the JVM

### ISSUE THREAD

**Issue by mmetman** [jpmml/pyspark2pmml#42]
Hi Villu,

Here's hoping you provide some help or insight on this one. I realise there's been a similar issue, however it seems to persist despite following your advice there. 

For the sake of completeness, I have first built the [jpmml-sparkml](https://github.com/jpmml/jpmml-sparkml) library as instructed. Indeed, this provides me with the `pmml-sparkml-2.5-SNAPSHOT.jar` archive. 

Subsequently, I run a spark job with the archive the canonical way, that is through

```shell
spark-submit --verbose --master local[*] --jars ~/jpmml-sparkml/pmml-sparkml/target/pmml-sparkml-2.5-SNAPSHOT.jar ~/scratchpad/spark/spark-test.py
```

As a minimal working example, the Python script contains the following:

```python
# ======================================================================================================
# imports
# ======================================================================================================
from pyspark.sql import SparkSession
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.pipeline import Pipeline
from pyspark.ml.classification import RandomForestClassifier
from pyspark2pmml import PMMLBuilder

def main():
    # ======================================================================================================
    # general parameters
    # ======================================================================================================
    train_path = "/home/maurits/var/collected/spark-test/training/*.parquet"
    
    # ======================================================================================================
    # get the (local) Spark session
    # ======================================================================================================
    spark = SparkSession.builder.getOrCreate()
    
    # ======================================================================================================
    # create a reference to the data
    # ======================================================================================================
    train_df = spark.read.parquet(train_path)
    
    # ======================================================================================================
    # set up a vector assembler
    # ======================================================================================================
    label     = " < redacted > "
    features  = sorted(set(train_df.columns).difference([label]))
    assembler = VectorAssembler(inputCols=train_df.columns, outputCol="features")
    
    # ======================================================================================================
    # set up an estimator
    # ======================================================================================================
    estimator = RandomForestClassifier(
        featuresCol="features",
        labelCol=label,
        maxDepth=5,
        impurity="entropy",
        numTrees=5,
        featureSubsetStrategy="auto",
        seed=9,
    )
    
    # ======================================================================================================
    # instantiate a pipeline and fit it to the data
    # ======================================================================================================
    pipeline = Pipeline(stages=[assembler, estimator])
    fitted = pipeline.fit(train_df)
    
    # ======================================================================================================
    # export to PMML
    # ======================================================================================================
    pmmlBuilder = PMMLBuilder(spark.sparkContext, train_df, fitted)
    pmmlBuilder.buildFile("spark-test.pmml")
    
if __name__ == "__main__":
    main()
```

Spark then confirms that the archive is included in the classpath:

```
Using properties file: null
24/12/09 11:48:25 WARN Utils: Your hostname, VDT238713 resolves to a loopback address: 127.0.1.1; using 172.20.226.124 instead (on interface eth0)
24/12/09 11:48:25 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Parsed arguments:
  master                  local[*]
  remote                  null
  deployMode              null
  executorMemory          null
  executorCores           null
  totalExecutorCores      null
  propertiesFile          null
  driverMemory            null
  driverCores             null
  driverExtraClassPath    null
  driverExtraLibraryPath  null
  driverExtraJavaOptions  null
  supervise               false
  queue                   null
  numExecutors            null
  files                   null
  pyFiles                 null
  archives                null
  mainClass               null
  primaryResource         file:/home/maurits/scratchpad/spark/spark-test.py
  name                    spark-test.py
  childArgs               []
  jars                    file:/home/maurits/jpmml-sparkml/pmml-sparkml/target/pmml-sparkml-2.5-SNAPSHOT.jar
  packages                null
  packagesExclusions      null
  repositories            null
  verbose                 true

Spark properties used, including those specified through
 --conf and those from the properties file null:



24/12/09 11:48:27 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Main class:
org.apache.spark.deploy.PythonRunner
Arguments:
file:/home/maurits/scratchpad/spark/spark-test.py
null
Spark config:
(spark.app.name,spark-test.py)
(spark.app.submitTime,1733741307612)
(spark.jars,file:///home/maurits/jpmml-sparkml/pmml-sparkml/target/pmml-sparkml-2.5-SNAPSHOT.jar)
(spark.master,local[*])
(spark.repl.local.jars,file:///home/maurits/jpmml-sparkml/pmml-sparkml/target/pmml-sparkml-2.5-SNAPSHOT.jar)
(spark.submit.deployMode,client)
(spark.submit.pyFiles,)
Classpath elements:
file:///home/maurits/jpmml-sparkml/pmml-sparkml/target/pmml-sparkml-2.5-SNAPSHOT.jar


24/12/09 11:48:29 INFO SparkContext: Running Spark version 3.5.3
24/12/09 11:48:29 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
24/12/09 11:48:29 INFO SparkContext: Java version 17.0.13
24/12/09 11:48:29 INFO ResourceUtils: ==============================================================
24/12/09 11:48:29 INFO ResourceUtils: No custom resources configured for spark.driver.
24/12/09 11:48:29 INFO ResourceUtils: ==============================================================
24/12/09 11:48:29 INFO SparkContext: Submitted application: spark-test.py
```

Nevertheless, the PMML conversion fails with the following error:
```
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/home/maurits/lib/spark-3.5.3-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maurits/lib/spark-3.5.3-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maurits/lib/spark-3.5.3-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
Traceback (most recent call last):
  File "/home/maurits/scratchpad/spark/spark-test.py", line 59, in <module>
    main()
  File "/home/maurits/scratchpad/spark/spark-test.py", line 55, in main
    pmmlBuilder = PMMLBuilder(spark.sparkContext, train_df, fitted)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maurits/.cache/pypoetry/virtualenvs/rs-ai-q3iyIEJ0-py3.12/lib/python3.12/site-packages/pyspark2pmml/__init__.py", line 12, in __init__
    javaPmmlBuilderClass = sc._jvm.org.jpmml.sparkml.PMMLBuilder
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maurits/lib/spark-3.5.3-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1664, in __getattr__
py4j.protocol.Py4JError: org.jpmml.sparkml.PMMLBuilder does not exist in the JVM
Exception in thread "Thread-5" java.lang.NoClassDefFoundError: jakarta/xml/bind/JAXBException
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at py4j.reflection.CurrentThreadClassLoadingStrategy.classForName(CurrentThreadClassLoadingStrategy.java:40)
        at py4j.reflection.ReflectionUtil.classForName(ReflectionUtil.java:51)
        at py4j.reflection.TypeUtil.forName(TypeUtil.java:243)
        at py4j.commands.ReflectionCommand.getUnknownMember(ReflectionCommand.java:175)
        at py4j.commands.ReflectionCommand.execute(ReflectionCommand.java:87)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: jakarta.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 10 more
```

This is especially unexpected since the archive does in fact seem to contain the class, as confirmed by `jar -tf ~/jpmml-sparkml/pmml-sparkml/target/pmml-sparkml-2.5-SNAPSHOT.jar`:

```
[...]
org/jpmml/sparkml/PMMLBuilder$1.class
org/jpmml/sparkml/PMMLBuilder$2.class
org/jpmml/sparkml/PMMLBuilder$Verification.class
org/jpmml/sparkml/PMMLBuilder.class
[...]
```

Obviously, I may be handling things incorrectly from my end, but if so please let me know. If you need some extra info I'd be happy to provide it of course. 

Thanks in advance,

Maurits

**Comment by vruusmann** [comment]
The `PMMLBuilder` class cannot be instantiated, because your Apache Spark application classpath is missing some supporting classes - Jakarta XML Binding API and runtime (this is needed for parsing the XML PMML document into and in-memory PMML object )

To quote:
```
Caused by: java.lang.ClassNotFoundException: jakarta.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
```

Right now you've added the `org.jpmml:pmml-sparkml:2.5-SNAPSHOT` artifact to Pyspark using the `--jars` command-line option.

The `--jars` option assumes a "uber" JAR file - the `PMMLBuilder` class together with all its supporting classes packaged into one JAR file. Your locally built `~/maurits/jpmml-sparkml/pmml-sparkml/target/pmml-sparkml-2.5-SNAPSHOT.jar` JAR file (approximate size 200 kB) does not  meet this requirement - it contains the `PMMLBulder` class, but it does not contain any supporting classes (such as the Jakarta XML Binding classes).

If you want to keep using the `--jars` command-line option, then you should use the `jpmml-sparkml-executable-${version}.jar` uber-JAR file (approximate size 6+ MB).

You can find a full history of release versions of this uber-JAR file here:
https://github.com/jpmml/jpmml-sparkml/releases/

For Apache Spark 3.5.X, use this one:
https://github.com/jpmml/jpmml-sparkml/releases/tag/2.5.0

However, if you want to keep using your locally built `~/maurits/jpmml-sparkml/pmml-sparkml/target/pmml-sparkml-2.5-SNAPSHOT.jar` JAR file (perhaps you made some customizations there?), then use the `--packages` command-line option instead. The `--packages` option parses the Apache Maven `pom.xml` that is included in this JAR file, and will download all the required transitive dependencies automatically, hence eliminating the possibility of `java.lang.ClassNotFoundException`.

**Comment by vruusmann** [comment]
@mmetman Pay attention, the project's README file tells you to use the `--packages` command-line option (not the `--jars` option):
https://github.com/jpmml/pyspark2pmml?tab=readme-ov-file#configuration-and-usage

Launching core:
```
pyspark --packages org.jpmml:pmml-sparkml:${version}
```

**Comment by mmetman** [comment]
Hi Villu,

Apologies, I seem to have had those run-time arguments confused then. Thanks for claryfing.

I now invoke spark as you specified above (either through `spark-submit` or `pyspark`). Indeed, dependencies are downloaded from the repository directly and added to the classpath as expected:
```
[...]
        :: modules in use:
        com.fasterxml.jackson.core#jackson-annotations;2.13.3 from central in [default]
        com.google.guava#guava;33.0.0-jre from central in [default]
        com.sun.activation#jakarta.activation;2.0.1 from central in [default]
        com.sun.istack#istack-commons-runtime;4.0.1 from central in [default]
        jakarta.xml.bind#jakarta.xml.bind-api;3.0.1 from central in [default]
        org.glassfish.jaxb#jaxb-core;3.0.2 from central in [default]
        org.glassfish.jaxb#jaxb-runtime;3.0.2 from central in [default]
        org.jpmml#pmml-converter;1.5.6 from central in [default]
        org.jpmml#pmml-converter-testing;1.5.6 from central in [default]
        org.jpmml#pmml-model;1.6.4 from central in [default]
        org.jpmml#pmml-model-metro;1.6.4 from central in [default]
        org.jpmml#pmml-sparkml;2.5.1 from central in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   12  |   12  |   12  |   0   ||   12  |   12  |
        ---------------------------------------------------------------------
[...]
Classpath elements:
file:///home/maurits/.ivy2/jars/org.jpmml_pmml-sparkml-2.5.1.jar
file:///home/maurits/.ivy2/jars/org.jpmml_pmml-converter-1.5.6.jar
file:///home/maurits/.ivy2/jars/org.jpmml_pmml-converter-testing-1.5.6.jar
file:///home/maurits/.ivy2/jars/org.jpmml_pmml-model-metro-1.6.4.jar
file:///home/maurits/.ivy2/jars/com.google.guava_guava-33.0.0-jre.jar
file:///home/maurits/.ivy2/jars/org.jpmml_pmml-model-1.6.4.jar
file:///home/maurits/.ivy2/jars/org.glassfish.jaxb_jaxb-runtime-3.0.2.jar
file:///home/maurits/.ivy2/jars/com.fasterxml.jackson.core_jackson-annotations-2.13.3.jar
file:///home/maurits/.ivy2/jars/jakarta.xml.bind_jakarta.xml.bind-api-3.0.1.jar
file:///home/maurits/.ivy2/jars/com.sun.activation_jakarta.activation-2.0.1.jar
file:///home/maurits/.ivy2/jars/org.glassfish.jaxb_jaxb-core-3.0.2.jar
file:///home/maurits/.ivy2/jars/com.sun.istack_istack-commons-runtime-4.0.1.jar
[...]
```
Unfortunately though, the issue persists and the application ultimately fails, producing the same traceback. This is surprising, since the XML binding module is now included explicitly in the above excerpt. Manually exposing the XML binding API through e.g. `pyspark --packages org.jpmml:pmml-sparkml:2.5.1,jakarta.xml.bind:jakarta.xml.bind-api:3.0.1` offers no improvement. Would you happen to know if this is some usage error on my end?

**Comment by vruusmann** [comment]
> Would you happen to know if this is some usage error on my end?

I vaguely remember that the behaviour of the `--packages` command-line option is Apache Spark version dependent. It downloads and installs the transitive dependencies correctly for some generations but not for the others. Looks like the Apache Spark 3.5.X generation belongs to the latter category.

Also, please check, perhaps the command works correctly on the second time you execute it? I also kind of vaguely remember that the first execution downloads the artifacts, but does not add them to the classpath. Only the second execution, which finds all the artifacts nicely in the local repository, can have the classpath correctly set up and initialized.

**Comment by vruusmann** [comment]
@mmetman Try the `--jars` command-line option with the pre-built JPMML-SparkML command-line application. This uber-JAR file has all dependencies included, so it does not need to interact with external JAR repositories, and is completely independent of the classpath contents:

```
spark-submit --jars  pmml-sparkml-example-executable-2.5.0.jar ...
```

You can get my pre-built release JARs from here:
https://github.com/jpmml/jpmml-sparkml/releases/

**Comment by mmetman** [comment]
I've had a go at your suggestions. Interestingly, the issue persists even when using the uber jar as suggested.

Nevertheless, I've now had a succesful run using an older version of Spark, that is `3.4.4` and `spark-submit --packages org.jpmml:pmml-sparkml:2.4.1 [...]`. Apparently, the Spark version does indeed seem to play a role in this behaviour. 

So for now I'll simply stick to using that version. If you'd like me to pass you any further info I could do that. In any case, thanks again for helping out.

**Comment by vruusmann** [comment]
> Apparently, the Spark version does indeed seem to play a role in this behaviour.

If you have time to triangulate this more, then you should consider filing a bug report against the Apache Spark project. I don't think this issue is specific to the JPMML-SparkML library; this should affect all 3rd party libraries.

> If you'd like me to pass you any further info I could do that.

I hope that this issue should be easily reproducible by anyone, including myself.

The interesting thing is that using a 3rd party library only fails when working with `--jars` and `--packages` command-line options. If you include the JPMML-SparkML dependency into your Spark application "directly" (as a dependency declaration in `pom.xml` file), it should work.

For example, the JPMML-SparkML library includes integration testing suite, and these pass cleanly on Apache Spark 3.5.X:
https://github.com/jpmml/jpmml-sparkml/actions/runs/9595343578
